### PR TITLE
Automatic Doc Type mapping

### PR DESCRIPTION
**Pull request by simion**
I've documented it in README, no point of explaining it here 😄

### CODE REVIEW

**Comment by laurentguilbert** [comment]
Looks good ! I'll write the tests this afternoon, don't bother.

**Comment by simion** [comment]
@laurentguilbert done, wrote tests which verify auto doc type mapping (including computing custom fields).

**Comment by laurentguilbert** [comment]
Awesome, it's merged :wink:

**Comment by simion** [comment]
Cool, thanks! I'll use the project in production as soon you can release a new version on pip 😉 Thanks alot

**Comment by laurentguilbert** [comment]
You should be good to go now.

**Comment by simion** [comment]
Awesome, thanks!

**Pull request merged**
