### PR TITLE
es_rebuild_index command

### PR DESCRIPTION
**Pull request by simion**
Implemented `es_rebuild_index` command, which compares data from ES with queryset and does the required operations (update/delete). 
The interesting part of this command is that it works with very high volumes of data. When you have a dozen of millions of record in database, you cannot use "queryset.all()" :)

I know it doesn't really follow the design pattern of the other commands (dry run, result), but that's how i needed it to be implemented (using pks, not objects). 
Sadly I haven't had time to implement tests, nor update the readme. If you could help me with that, it would be great.

There's also a dead simple progress bar, maybe you want to use it on other commands too.

Kind regards,

ps: coverage would most likely not be 100% anymore

### CODE REVIEW

**Comment by simion** [comment]
Finally, tests working and coverage 100%. @laurentguilbert can you please merge the changes? Thanks 😉

**Comment by laurentguilbert** [comment]
Hi,

I actually have a few issues with this PR in terms of design.

Right now `es_rebuild_index` doesn't account for `obj.is_indexable()` which means potentially unwanted objects in ES.

A cleanup command deleting unused documents might be nice, although I kinda doubt its utility to be honest :smiley:

A progress bar is a good idea, I implemented one for `es_create_documents` in my latest commits :+1: 

Other than that `es_rebuild_index` does the same job as `es_create_documents` in terms of updating. 

Is `queryset.all()` a real performance bottleneck for your use case ? Your solution using `.values_list('pk')` is interesting and might be a better solution. 
I could also add the async option to `es_create_documents` in order to speed things up I guess.

Let me know what you think I'm always open to discussion.

**Comment by simion** [comment]
Indeed, I forgot about `is_indexable()`, that can be fixed.
For me, `queryset.all()` is a bottleneck, because the largest table I need to index has more than 30 million rows, and lots of columns, including text ones. 

I can pull from upstream and use your progressbar if you'd like.

From my experience, the cleanup command is really useful, at large scale many things can go wrong, and objects will remain stale in ES. A "sync" command is preferred here, rather than separate cleanup / index. 

What do you think?

**Comment by simion** [comment]
I made the progress bar changes. The issue with `is_indexable` remains, because I would like not to retrieve the model instance when iterating over pks, rather than run or apply the task directly. It's a big performance bottleneck, for me at least.

**Comment by simion** [comment]
A solution can be to check `is_indexable()` inside the task logic, right after retrieving the model instance from database, and raise celery.exceptions.Ignore() if it's not indexable.

**Comment by laurentguilbert** [comment]
Yeah I'm working on something on my end. 

I am improving `es_create_documents` to work with pks instead of querysets and also add a `--cleanup` option. Feels better than having a separate command to me.

**Comment by simion** [comment]
That sounds good. I was also thinking of using python multiprocessing module to add tasks or index objects in a multi-threaded way. I did this in other projects and works like a charm. I almost always use it with 6-8 threads.

**Comment by laurentguilbert** [comment]
Hmm yes might be a better solution than using async for the management command. I'm on it. :+1:

**Comment by simion** [comment]
Give me a minute to upload a gist with the helper method i created for multiprocessing, maybe you take some ideas of it.

**Comment by laurentguilbert** [comment]
Sure, thanks

**Comment by simion** [comment]
https://gist.github.com/simion/4447668fd69ae191b5f42895fa26017f
There are some design issues, but that's the implementation made at the time, maybe you find it useful.

**Pull request closed without merging**
